- name: Ensure apt cache updated
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

# - name: Ensure python3 installed
#   raw: test -e /usr/bin/python3 || (apt-get update && apt-get install -y python3)

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Install docker and compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure docker started
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Ensure compose root directory exists
  file:
    path: "{{ compose_dir | default('/home/' + ansible_user + '/ci-cd-gcp') }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
