pipeline {
    agent any
    stage {
        stage('Decide and Trigger Pipelines') {
            steps {
                script {
                    def changedFiles = sh(
                        script: 'git diff --name-only HEAD~1 HEAD',
                        returnStdout: true
                    ).trim().split('\n')

                    if (changedFiles.any { it.startsWith('application/server/') }) {
                        build job: 'ci-cd-gcp-backend', wait: false
                }
                    if (changedFiles.any { it.startsWith('application/public/') }) {
                        build job: 'ci-cd-gcp-frontend', wait: false
            }
        }
    }
}
    }
}
