pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/modpanyakorn/ci-cd-gcp.git'
            }
        }

        stage('Decide and Trigger Pipelines') {
            parallel {
                stage('Backend Trigger') {
                    when {
                        changeset pattern: 'application/server/**', comparator: 'ANT'
                    }
                    steps {
                        script {
                            echo '>>> Changes detected in backend → Trigger backend pipeline'
                            build job: 'ci-cd-gcp-backend', wait: false
                        }
                    }
                }

                stage('Frontend Trigger') {
                    when {
                        changeset pattern: 'application/public/**', comparator: 'ANT'
                    }
                    steps {
                        script {
                            echo '>>> Changes detected in frontend → Trigger frontend pipeline'
                            build job: 'ci-cd-gcp-frontend', wait: false
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo '✅ Dispatcher finished (triggered required pipelines)'
        }
    }
}
