- name: Ensure frontend directory exists
  file:
    path: /home/{{ ansible_user }}/ci-cd-gcp/frontend
    state: directory

- name: Render .env for frontend
  template:
    src: .env.j2
    dest: /home/{{ ansible_user }}/ci-cd-gcp/frontend/.env

- name: Load multiple variable files for templates render
  ansible.builtin.include_vars:
    file: "{{ item }}"
  loop:
    - ../../inventory/group_vars/backend.yml
    - ../../inventory/group_vars/db.yml
  tags: ["load-vars"]

- name: Render nginx.conf
  template:
    src: nginx.conf.j2
    dest: /home/{{ ansible_user }}/ci-cd-gcp/frontend/nginx.conf

- name: Render docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/ci-cd-gcp/frontend/docker-compose.yml

# - name: Deploy frontend stack
#   command: docker compose up -d --build
#   args:
#     chdir: /home/{{ ansible_user }}/ci-cd-gcp/frontend

- name: Deploy docker-compose.yml # use thist instead
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/ci-cd-gcp/frontend
    build: "always"
    state: present
