# roles/devops/tasks/main.yml

- name: Setup devops services (directories, docker-compose, vault, etc.)
  ansible.builtin.include_tasks: setup-services.yml
  tags: ["setup"]

- name: Push secrets into Vault
  ansible.builtin.include_tasks: local-push-secert-to-vault.yml
  tags: ["vault", "secrets"]
