jenkins:
  port: 8000
grafana:
  port: 8001
prometheus:
  port: 8002
sonarqube:
  port: 8003
mongo_express:
  port: 8004
  mongodb_host: "{{ hostvars[groups['db'][0]].private_ip }}"
  mongodb_port: "{{ mongodb.port }}"
  username: "admin"
  password: "1234"
vault:
  mount_path: "ci-cd-gcp"
  port: 8200
  env:
    VAULT_ADDR: http://0.0.0.0:8200
    VAULT_DEV_ROOT_TOKEN_ID: root-token
    VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
